### ISSUE TITLE
Can't import odo 

### ISSUE THREAD

**Issue by sterlinm** [ContinuumIO/odo#146]
I get an error when I attempt to import odo.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f8e6b93414f5> in <module>()
----> 1 from odo import odo

C:\Users\~AppData\Local\Continuum\Anaconda\lib\site-packages\odo\__init__.py in <module>()
     10 
     11 from .utils import ignoring
---> 12 from .convert import convert
     13 from .append import append
     14 from .resource import resource

C:\Users\~AppData\Local\Continuum\Anaconda\lib\site-packages\odo\convert.py in <module>()
      3 import numpy as np
      4 import pandas as pd
----> 5 from datashape.predicates import isscalar
      6 from toolz import concat, curry, partition_all
      7 from collections import Iterator, Iterable

ImportError: cannot import name isscalar

**Comment by mrocklin** [comment]
I suspect that your datashape is very out of date.   If you install by conda this is taken care of and if you didn't have datashape then this is taken care of.  But if you installed anaconda a while ago and then install with `pip` then you run into a version mismatch.

Probably we should state that version dependence explicitly in the requirements.txt file.  This is fixed in https://github.com/ContinuumIO/odo/commit/8448fa0926e488bb28860fba9b4e1d6a4ba5e4f8 .

**Comment by sterlinm** [comment]
That fixed it. Just installed fresh Anaconda two days ago, so a bit surprising but updating with conda did it. Thanks!
